feat: Add guardrails span kind
Arize-ai/openinference pull request #540
Opened 2024-06-24 21:43 UTC by nate-mar

Add guardrails span kind to list of span kinds

2024-06-24 21:47 UTC, nate-mar commented
I have read the CLA Document and I hereby sign the CLA

2024-06-24 22:14 UTC, mikeldking commented on js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
> +  GUARDRAILS = "guardrails",
```suggestion
  GUARDRAIL = "guardrail",
```
Can we make it singular? Also what would be the typical contents of a guardrail span?

2024-06-24 22:16 UTC, mikeldking requested changes
Let's add spec changes and also python changes

2024-06-24 22:59 UTC, nate-mar commented
@mikeldking will do -- can you point me to where in the spec file I should add this span kind? I can't seem to locate a place in the spec where these span kinds are comprehensively listed; I only see a list of example span kinds under the `openinference.span_kind` attribute.

2024-06-25 03:10 UTC, mikeldking commented
> @mikeldking will do -- can you point me to where in the spec file I should add this span kind? I can't seem to locate a place in the spec where these span kinds are comprehensively listed; I only see a list of example span kinds under the `openinference.span_kind` attribute.

Yes, as this is technically an attribute value it's not bound by any convention. But at least describing the value here would be ideal: https://github.com/Arize-ai/openinference/blob/main/spec/traces.md

2024-06-25 03:29 UTC, mikeldking commented on js/packages/openinference-semantic-conventions/src/trace/SemanticConventions.ts
> +  GUARDRAIL = "guardrail",
These changes require something called a changeset to be deployed: https://github.com/Arize-ai/openinference/blob/main/js/DEVELOPMENT.md#changesets

2024-06-25 20:12 UTC, mikeldking approved these changes
Exciting!

2024-06-25 20:44 UTC, merged